sudo: required
language: cpp

addons:
    apt:
        packages:
            - gcc-5
            - g++-5

before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install cmake

install:
    mkdir build && cd build && cmake -DENABLE_TESTS=ON .. && make

script:
    cd build && make test
