sudo: required
language: cpp

addons:
    apt:
        packages:
            - gcc-5
            - g++-5
            - cmake
        sources:
            - ubuntu-toolchain-r-test

install:
    mkdir build && cd build && cmake -DENABLE_TESTS=ON .. && make

script:
    cd build && make test
