sudo: false
language: cpp
compiler: gcc

cache: apt

addons:
    apt:
        packages:
            - gcc-6
            - g++-6
            - cmake-data
            - cmake
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

before_install:
    - mkdir build && cd build
    - mkdir 3rd && cd 3rd
    - wget https://github.com/google/googletest/archive/release-1.8.0.zip
    - unzip release-1.8.0.zip
    - cd ..

install:
    - cmake -DCMAKE_CXX_COMPILER=g++-6 -DBUILD_TESTS=ON ..
    - make

script:
    - ./singletonTest
