language: cpp

before_install:
    - sudo apt-get g++-5
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install cmake

script:
    mkdir build && cd build && cmake -DENABLE_TESTS=ON .. && make && make test
