sudo: required
language: cpp

addons:
    apt:
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
            - libgtest-dev
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

before_script:
    - install -d gtest_build
    - pushd gtest_build
    - cmake -DCMAKE_CXX_COMPILER=clang++-3.7 /usr/src/gtest/
    - make
    - sudo cp *.a /usr/lib
    - popd


script:
    - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
    - mkdir build && cd build
    - cmake -DENABLE_TESTS=ON ..
    - make
    - make test
