sudo: required
language: cpp
compiler: gcc

cache: apt

addons:
    apt:
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

before_install:
    - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
    - mkdir build && cd build
    - mkdir 3rd && cd 3rd
    - wget https://github.com/google/googletest/archive/release-1.8.0.zip
    - unzip release-1.8.0.zip
    - cd ..

install:
    - cmake -DENABLE_TESTS=ON ..
    - make

script:
    - ./singletonTest
