sudo: required
language: cpp
compiler: gcc

addons:
    apt:
        packages:
            - gcc-5
            - g++-5
            - cmake-data
            - cmake
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports

script:
    - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
    - mkdir build && cd build
    - cmake -DENABLE_TESTS=ON ..
    - make
    - make test
